UPDATE "feature_names" SET text = 'ostření', description = 'Rychlost, přesnost a hlučnost ostření' WHERE feature_names_id = 60;
UPDATE "feature_names" SET text = 'obsah balení', description = 'Obsah balení (sluchátka, obal, folie, nabíječka)' WHERE feature_names_id = 1;
UPDATE "feature_names" SET text = 'displej', description = 'Kvalita displeje' WHERE feature_names_id = 50;
UPDATE "feature_names" SET text = 'nabíjení', description = 'Rychlost nabíjení' WHERE feature_names_id = 21;
UPDATE "feature_names" SET text = 'displej', description = 'Kvalita displeje, hustota pixelů, barevné podání' WHERE feature_names_id = 12;
UPDATE "feature_names" SET text = 'režimy', description = 'Množství režimů' WHERE feature_names_id = 32;
UPDATE "feature_names" SET text = 'nabíjení', description = 'Způsob nabíjení, přítomnost nabíjecího kabelu' WHERE feature_names_id = 47;
UPDATE "feature_names" SET text = 'rychlost snímání', description = 'Rychlost seriového snímání' WHERE feature_names_id = 31;
UPDATE "feature_names" SET text = 'možnosti nastavení', description = 'Rozsah možností nastavení' WHERE feature_names_id = 53;
UPDATE "feature_names" SET text = 'rozsah zoomu', description = 'Rozsah zoomu' WHERE feature_names_id = 63;
UPDATE "feature_names" SET text = 'kresba', description = 'Ostrost kresby, množství detailů' WHERE feature_names_id = 59;
UPDATE "feature_names" SET text = 'konektory', description = 'Přítomnost konektorů USB, microUSB, 3.5 jack' WHERE feature_names_id = 13;
UPDATE "feature_names" SET text = 'kvalitní snímky', description = 'Kvalita výsledného snímku' WHERE feature_names_id = 33;
UPDATE "feature_names" SET text = 'ovládání', description = 'Uživatelské rozhraní, přehlednost menu, jednoduchost ovládání' WHERE feature_names_id = 49;
UPDATE "feature_names" SET text = 'raw formát', description = 'Možnost ukládat do RAW formátu, kvalita RAWu' WHERE feature_names_id = 40;
UPDATE "feature_names" SET text = 'video', description = 'Kvalita pořízeného vydea, 4K video' WHERE feature_names_id = 34;
UPDATE "feature_names" SET text = 'cena', description = 'Cena' WHERE feature_names_id = 37;
UPDATE "feature_names" SET text = 'odolnost', description = 'Odolnost proti prachu, vodě a pádu' WHERE feature_names_id = 38;
UPDATE "feature_names" SET text = 'paměť', description = 'Velikost vnitřní paměti' WHERE feature_names_id = 25;
UPDATE "feature_names" SET text = 'blesk', description = 'Přítomnost a výkon blesku' WHERE feature_names_id = 48;
UPDATE "feature_names" SET text = 'padne do ruky', description = 'Jak dobře se drží v ruce, zda neklouže' WHERE feature_names_id = 57;
UPDATE "feature_names" SET text = 'rozměry, hmotnost', description = 'Rozměry a hmotnost' WHERE feature_names_id = 44;
UPDATE "feature_names" SET text = 'zoom', description = 'Rozsah zoomu' WHERE feature_names_id = 51;
UPDATE "feature_names" SET text = 'rozlišení', description = 'Hodnota rozlišení' WHERE feature_names_id = 28;
UPDATE "feature_names" SET text = 'odolnost', description = 'Odolnost proti prachu, vodě a pádu' WHERE feature_names_id = 19;
UPDATE "feature_names" SET text = 'barevné podání', description = 'Barevné podání snímku' WHERE feature_names_id = 55;
UPDATE "feature_names" SET text = 'obrazová kvalita', description = 'Kvalita výsledných fotografií' WHERE feature_names_id = 29;
UPDATE "feature_names" SET text = 'kvalita zpracování', description = 'Kvalita konstrukce, použitých materiálů a celkové zpracování' WHERE feature_names_id = 9;
UPDATE "feature_names" SET text = 'čtečka otisku prstu', description = 'Přítomnost a přesnost čtečky otisků prstů' WHERE feature_names_id = 17;
UPDATE "feature_names" SET text = 'celkový dojem', description = 'Celkový dojem' WHERE feature_names_id = 0;
UPDATE "feature_names" SET text = 'výkon', description = 'Výkon' WHERE feature_names_id = 16;
UPDATE "feature_names" SET text = 'ovládání', description = 'Ovládání' WHERE feature_names_id = 24;
UPDATE "feature_names" SET text = 'baterie', description = 'Kapacita a výdrž baterie' WHERE feature_names_id = 3;
UPDATE "feature_names" SET text = 'fotoaparát', description = 'Kvalita fotoaparátu' WHERE feature_names_id = 15;
UPDATE "feature_names" SET text = 'rozměry a hmotnost', description = 'Rozměry a hmotnost' WHERE feature_names_id = 11;
UPDATE "feature_names" SET text = 'kvalita zvuku', description = 'Kvalita zvuku' WHERE feature_names_id = 5;
UPDATE "feature_names" SET text = 'světelnost', description = 'Světelnost' WHERE feature_names_id = 61;
UPDATE "feature_names" SET text = 'cena', description = 'Cena' WHERE feature_names_id = 64;
UPDATE "feature_names" SET text = 'obrazové vady', description = 'Chromatická aberace, vinětace, soudkovitost' WHERE feature_names_id = 62;
UPDATE "feature_names" SET text = 'ergonomie', description = 'Rozmístění ovládacích prvků' WHERE feature_names_id = 41;
UPDATE "feature_names" SET text = 'slot na karty', description = 'Počet slotů a podpora různých typů karet' WHERE feature_names_id = 27;
UPDATE "feature_names" SET text = 'ostření', description = 'Rychlost, přesnost a hlučnost ostření' WHERE feature_names_id = 39;
UPDATE "feature_names" SET text = 'operační systém', description = 'Rychlost, spolehlivost, plynulost operačního systému' WHERE feature_names_id = 20;
UPDATE "feature_names" SET text = 'konektivita', description = 'Podpora wifi, bluetooth, nfc, 4g sítí' WHERE feature_names_id = 14;
UPDATE "feature_names" SET text = 'slot na karty', description = 'Přítomnost slotu na přídavnou SD nebo sim kartu' WHERE feature_names_id = 4;
UPDATE "feature_names" SET text = 'velikost paměti', description = 'Velikost paměti' WHERE feature_names_id = 7;
UPDATE "feature_names" SET text = 'cena', description = 'Cena' WHERE feature_names_id = 2;
UPDATE "feature_names" SET text = 'notifikační dioda, svítilna, blesk', description = 'Přítomnost notifikační diody, výkon svítilny a blesku' WHERE feature_names_id = 10;
UPDATE "feature_names" SET text = 'rozměry a hmotnost', description = 'Rozměry a hmotnost' WHERE feature_names_id = 68;
UPDATE "feature_names" SET text = 'obrazová kvalita', description = 'Kvalita výsledného snímku' WHERE feature_names_id = 65;
UPDATE "feature_names" SET text = 'stabilizace', description = 'Přítomnost a účinnost stabilizace objektivu' WHERE feature_names_id = 67;
UPDATE "feature_names" SET text = 'bokeh', description = 'Vzhled rozostřených oblastí snímků nacházejících se mimo hloubku ostrosti' WHERE feature_names_id = 70;
UPDATE "feature_names" SET text = 'konstrukce', description = 'Robustnost, odolnost a kvalita konstrukce, plastové nebo kovové provedení bajonetu' WHERE feature_names_id = 66;
UPDATE "feature_names" SET text = 'výdrž baterie', description = 'Kapacita a výdrž baterie' WHERE feature_names_id = 36;
UPDATE "feature_names" SET text = 'objektiv ', description = 'Kvalita objektivu (světelnost, clona, kresba), množství výměnných objektivů' WHERE feature_names_id = 52;
UPDATE "feature_names" SET text = 'konektivita', description = 'Podpora wifi, bluetooth, nfc' WHERE feature_names_id = 30;
UPDATE "feature_names" SET text = 'snímač', description = 'Velikost a kvalita snímače' WHERE feature_names_id = 45;
UPDATE "feature_names" SET text = 'úchop', description = 'Jak dobře se drží v ruce, grip' WHERE feature_names_id = 54;
UPDATE "feature_names" SET text = 'šum', description = 'Citlivost snímače, potlačení šumu' WHERE feature_names_id = 35;
UPDATE "feature_names" SET text = 'zpracování', description = 'Kvalita konstrukce, použitých materiálů a celkové zpracování' WHERE feature_names_id = 42;
UPDATE "feature_names" SET text = 'stabilizace', description = 'Přítomnost a účinnost stabilizace' WHERE feature_names_id = 26;
UPDATE "feature_names" SET text = 'výkon při nepříznivém světle', description = 'Výkon v protisvětle nebo šeru' WHERE feature_names_id = 46;
UPDATE "feature_names" SET text = 'sluneční clona', description = 'Zda je k objektivu přibalena sluneční clona' WHERE feature_names_id = 69;
UPDATE "feature_names" SET text = 'tlačítka', description = 'Přítomnost a kvalita tlačítek nebo hardwarové klávesnice' WHERE feature_names_id = 58;